### ISSUE TITLE
Add configuration for different comments systems

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/sphinx-comments#1]
Something like this structure in `sphinx_comments` configuration dictionary

```yaml
comments:
  disqus:
    key: val
  hypothesis:
    these: configure
  utterances:
    each: comments-engine
  dokieli:
    key: val
```
